# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nrodrigu <nrodrigu@student.42urduliz.co    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/04 11:50:59 by nrodrigu          #+#    #+#              #
#    Updated: 2022/09/04 11:53:50 by nrodrigu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


CFLAGS = -Wall -Wextra -Werror
NAME = libft.a

program: 

		
clean:
		@rm -f *.o

fclean: clean 
		@rm -f $(NAME)
